### ISSUE TITLE
AudioWorklet audio glitches

### ISSUE THREAD

**Issue by bitworking** [jet2jet/js-synthesizer#1]
Hi, thanks for this nice library. I've tried the AudioWorklet implementation and got a lot of audio glitches when I move the browser window etc. In the main thread it runs very smoothly. Did you encounter the same problem? I've tested it on Chrome/Windows.

**Comment by jet2jet** [comment]
Thanks for the report.

In AudioWorklet, though WebAssembly works on it, the render process is required to perform very quickly. According to the current Web Audio specification, only [128 frames (= one render quantum) can be rendered per one process](https://www.w3.org/TR/webaudio/#dom-audioworkletprocessor-process). So if sample rate is 48,000 (Hz), one process can only spend around 2.67ms (1000*128/48000) without glitches.

Currently I think Web Worker is the best to run js-synthesizer, and AudioWorklet should just receive the generated buffer from Web Worker and render it. [js-sequencer](https://github.com/jet2jet/js-sequencer) is using this method (around [worker](https://github.com/jet2jet/js-sequencer/tree/master/src/worker) and [worklet](https://github.com/jet2jet/js-sequencer/tree/master/src/worklet) directories), so if necessary please refer it. (This may be complex, but may work more properly.)

**Comment by bitworking** [comment]
Thanks for this great response. I am new to WebAssembly and AudioWorklets, so I have to learn a few things.

Ah nice, didn't saw this project. I once wrote a Midi sequencer with Flex and the [Project Alchemy](https://labs.adobe.com/technologies/alchemy/). I also used FluidSynth and did the MIDI parsing in ActionScript. Nice to see another person with the same idea 😃👍
