### ISSUE TITLE
Module.asm is undefined

### ISSUE THREAD

**Issue by Zipdox** [jet2jet/js-synthesizer#13]
I'm trying to run some of the example code but when I run `synth.init(context.sampleRate)` this happens:
```
Uncaught TypeError: Module.asm is undefined
    _new_fluid_settings http://localhost/mmp-soundfont/libfluidsynth-2.1.3.js:4488
```

**Comment by Zipdox** [comment]
Ok it appears that I have to wait for things to initialize before I can run init. Please add this to the documentation.

**Comment by jet2jet** [comment]
Thanks for the report.

It's fact that we must wait for initializing WebAssembly, but actually not documented.
I'll keep open this issue until I write it to the document (and/or make the new API for 'wait for initialized')

**Comment by Zipdox** [comment]
I think better documentation in general would be useful. Perhaps  you could add docstrings to the code and use some tool to auto generate documentation. Some example code would also be useful.

**Comment by jet2jet** [comment]
I added the document to README.md 456ef86 .  
I'm also planning to add the new APIs.

**Comment by jet2jet** [comment]
> I'm also planning to add the new APIs.

I added `Synthesizer.waitForWasmInitialized` static method in commit c26b2ddd.

**Comment by jet2jet** [comment]
I released as v1.8.0 (with documentation).

**Comment by jet2jet** [comment]
Closing this issue. Feel free to reopen if some problems still persist.

**Comment by Zipdox** [comment]
Seems solved
