### ISSUE TITLE
Having trouble getting SMF data to play

### ISSUE THREAD

**Issue by mrvelic** [jet2jet/js-synthesizer#16]
I've initialised the audioworklet like this:
```javascript
        self.audioContext = new AudioContext();
        let soundFontPromise = this.audioContext.audioWorklet.addModule('libfluidsynth-2.1.3.js')
            .then(() => self.audioContext.audioWorklet.addModule("js-synthesizer.worklet.min.js"))
            .then(() => {
                self.synth = new AudioWorkletNodeSynthesizer();
                self.synth.init(self.audioContext.sampleRate);
                self.audioNode = self.synth.createAudioNode(self.audioContext);
                self.audioNode.connect(self.audioContext.destination);

                return axios
                    .get<ArrayBuffer>("LttPSF2.sf2", { responseType: 'arraybuffer' })
                    .then(x => self.synth.loadSFont(x.data))
                    .catch(console.error);
            });
```

And just as a test attempting to play a .mid file like this:
```javascript
        axios
            .get<ArrayBuffer>("faded.mid", { responseType: 'arraybuffer' })
            .then(x => synth.addSMFDataToPlayer(x.data))
            .then(() => console.log(synth.isInitialized()))
            .then(() => synth.retrievePlayerBpm().then(console.log))
            .then(() => synth.playPlayer())
            .then(() => console.log(synth.isPlaying()))
            .then(() => synth.waitForPlayerStopped())
            .then(() => synth.waitForVoicesStopped())
            .catch(console.error);
```

I have checked and both the sf2 file and the .mid file seem to load successfully, I get the BPM output in the console so it appears to be reading the .mid correctly too, but immediately after playPlayer() isPlaying() is false.

Any idea what I'm doing wrong?
Version is 1.7.0 from npm as well

**Comment by jet2jet** [comment]
It's because `isPlaying()` becomes `true` when an audio frame is rendered.
Since the rendering is processed asynchronously, the `isPlaying()` would not be `true` immediately after `playPlayer()` calls.

In this case, `isPlayingPlayer()` should return `true` after `playPlayer`, but currently returns `false` (bug).
I fixed it in commit 09a25f50, so you can use `isPlayingPlayer()` in next release.

**Comment by jet2jet** [comment]
>  I fixed it in commit 09a25f5, so you can use isPlayingPlayer() in next release.

I released as v1.8.0, so please use this version.

**Comment by mrvelic** [comment]
Thanks! I'll give it a go

**Comment by jet2jet** [comment]
Closing this issue. Feel free to reopen if some problems still persist.
