### ISSUE TITLE
Direct `MessagePort` API to synthesizer AudioWorklet?

### ISSUE THREAD

**Issue by micahscopes** [jet2jet/js-synthesizer#17]
I'm working on making a non-linear MIDI sequencer in an AudioWorklet and would like to test it out with js-synthesizer.  Is it possible to directly send MIDI events to a `JSSynth.AudioWorkletNodeSynthesizer` instance via its `MessagePort`?

**Comment by jet2jet** [comment]
Currently, to send something to AudioWorklet, you can use `callFunction` method in `AudioWorkletNodeSynthesizer`.  

```js
// in AudioWorklet (myworklet.js)
AudioWorkletGlobalScope.someFunction = (synth, param) => {
   // some implementation (synth is Synthesizer)
};

// in main thread
const context = new AudioContext();
await context.audioWorklet.addModule('myworklet.js'); // load your script
await context.audioWorklet.addModule('js-synthesizer.worklet.min.js'); // load js-synthesizer
const workletSynthesizer = new JSSynth.AudioWorkletNodeSynthesizer();
workletSynthesizer.init(context.sampleRate);
// you must first create AudioNode to use `callFunction`
const node = synth.createAudioNode(ac);
...
// sending `param` to `someFunction` in AudioWorklet
workletSynthesizer.callFunction('someFunction', param);
```

You can then process MIDI events in AudioWorklet, including calling `midi****` method for `synth` instance.

\# Currently (unfortunately) using `MessagePort` is not available, as well as transferring the port.

**Comment by micahscopes** [comment]
This is very helpful, thank you.  I think I'm understanding that two AudioWorklet processors will both have access to the same `AudioWorkletGlobalScope`, and that the `JSSynth.AudioWorkletNodeSynthesizer` worklet node includes a `callFunction` method to access arbitrary functions defined on the `AudioWorkletGlobalScope`?

Or maybe I'm getting this wrong?  What I'd like to be able to do is send midi note events from inside my custom sequencer AudioWorklet processor code over to the JSSynth audioworklet without passing data through the main thread, since there's lots of animation and interrupts happening in my main thread.

By the way, [the WAM project](https://www.webaudiomodules.org/wamsynths/dexed) _appears_ to have a `MessagePort` API for sending MIDI messages to worklets, although I can't manage to find clear, explicit documentation of it... the only documentation I can find is [this academic paper from 2015](https://www.webaudiomodules.org/docs/wampaper-smc2015.pdf).  But here are some clues that this maybe is the case:

- https://github.com/webaudiomodules/api/blob/master/wamsdk/wam-processor.js#L93-L104
- https://github.com/webaudiomodules/webdx7/blob/master/dist/wamsdk/wam-controller.js#L11-L25

WAM seems awesome, I just wish the documentation and website were much more organized and usable for developers.

**Comment by jet2jet** [comment]
> I think I'm understanding that two AudioWorklet processors will both have access to the same AudioWorkletGlobalScope, and that the JSSynth.AudioWorkletNodeSynthesizer worklet node includes a callFunction method to access arbitrary functions defined on the AudioWorkletGlobalScope?

That's true. `AudioWorkletGlobalScope` is shared between all scripts loaded into the (same) worklet, and calling `callFunction` from *main thread* will invoke shared `AudioWorkletGlobalScope.xxxx` (`xxxx` is the function) in the worklet.

**Comment by jet2jet** [comment]
Closing this issue. Feel free to reopen if some problems still persist.
