### ISSUE TITLE
Warning and looping questions

### ISSUE THREAD

**Issue by cwiggins999** [jet2jet/js-synthesizer#25]
js-synthesizer is working great so far for our project. A couple of questions:

Can warning messages such as these that go to the browser console be suppressed? Everything I've tested so far through my soundfont of choice sounds fine.
luidsynth: warning: Instrument '60's Organ 1': Some invalid generators were discarded

I'm using the sequencer built into libfluidsynth so far. Does it support looping of the current sequence? Or would I need to use js-sequencer for that?

Also is there a way to change the sequencer tempo? I see methogs for retriving the MIDITemp and Bpm.

**Comment by jet2jet** [comment]
There was no feature to suppress logs, and to setb looping for the player. Both are available in libfluidsynth, so I added following methods:

- `JSSynth.disableLogging` / `JSSynth.restoreLogging` -- change log output from libfluidsynth
- `ISynthesizer.setPlayerLoop` -- set loop for the player

I published v1.10.0 which includes the methods above, so please try it.

**Comment by cwiggins999** [comment]
Thank you very much! I will try these later today. Are the logging functions available from the non-worklet interface? I think everything I've been using so far was defined in Synthesizer.ts and I don't see the logging mentioned there.

**Comment by jet2jet** [comment]
> Are the logging functions available from the non-worklet interface?

`JSSynth.disableLogging` / `JSSynth.restoreLogging` can be called from the main code (non-worklet code), and the logging setting (enable/disable) will affect to the worklet code. (i.e. if calling `JSSynth.disableLogging` from the main code, the logs from the worklet will be suppressed.)

**Comment by cwiggins999** [comment]
Just got this into our app code and seems to be working well. Thanks again for the update!
